name: Thirdeye
favicon: null
layout_spectrum: 0.99904
typography_spectrum: 0.74855
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#2b353d'
    - '#70533e'
    - '#e5c9b6'
    - '#fefefe'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
