favicon: null
name: Thirdeye
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0
  brandStrength: 0
  lightness: 0
  brandColors:
    - '#020202'
    - '#2b353d'
    - '#70533e'
    - '#e5c9b6'
    - '#fefefe'
  rhythmicContrast: 0.1319149
typography_spectrum: 0.74855
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.99904
analytics:
  twitter: null
  google: null
  facebook: null
